### ISSUE TITLE
Missing easter egg

### ISSUE THREAD

**Issue by brisacier** [guillaume-girard/9darter#3]
Guten tag,

During our last webinar in Dusseldorf with some of my freundinen, I've heard of a hidden feature in your awesome web application. Some lad told me that if I scored a triple twenty, there would be a surprise, as he said, "very bold".

However, you may have a bug in your architecture since I can't seem to reproduce the case. No matter how much triple 20s I score (and I score a lot of them, tbh) nothing seems to happen.

Is that a known problem to you ? Is it intendend ? You're not my father ? So Kai isn't my brother ? Who is my real father ?

viel Spaß
Prof. von Brisacier

**Comment by guillaume-girard** [comment]
Corrected, commit 446655b
