### ISSUE TITLE
Ceci a t-il été codé avec le cul ?

### ISSUE THREAD

**Issue by manoncombe** [guillaume-girard/9darter#4]
Lorsqu'on fait un 301 ou 501 SANS le Double Out, le logiciel nous fait BUST lorsque l'on accède au score de 1.
Bien à vous,

CagSteve pour @guillaume-girard

**Comment by guillaume-girard** [comment]
Non reproduit sur ma machine.

Pouvez-vous préciser le navigateur utilisé ainsi que sa version svp.

En outre merci de préciser étape par étape le processus qui permet de déclencher le bug, typiquement : 
**Ce que je fais**
**Comportement attendu**
**Comportement observé**

A vous, roger.

**Comment by guillaume-girard** [comment]
[ndlr]

Dans script.js 

Games instanciés l. 866 && 886
isDoubleOut instancié l. 110
Tests isDoubleOut l. 216 && 244

**Comment by guillaume-girard** [comment]
Vu avec l'intéressé
